extends: eslint:recommended

parser: babel-eslint

env:
  node: true
  es6: true

rules:
  valid-jsdoc: error
  curly: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  no-alert: error
  no-eval: error
  no-implied-eval: error
  no-invalid-this: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-return-await: error
  strict:
    - error
    - global
  require-await: error
  no-undef-init: error
  global-require: error
  block-spacing: error
  array-bracket-spacing:
    - error
    - never
  brace-style: error
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - 100
  no-tabs: error
  no-trailing-spaces: error
  arrow-spacing: error
  constructor-super: error
  no-const-assign: error
  no-duplicate-imports: error
  no-var: error
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
